name: imotep
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.1.0=h2466b09_2
  - brotli-bin=1.1.0=h2466b09_2
  - bzip2=1.0.8=h2466b09_7
  - ca-certificates=2025.8.3=h4c7d964_0
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py312h4389bb4_0
  - contourpy=1.3.1=py312hd5eb7cc_0
  - cycler=0.12.1=pyhd8ed1ab_1
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - fonttools=4.56.0=py312h31fea79_0
  - freetype=2.12.1=hdaf720e_2
  - glib=2.82.2=h3d4babf_1
  - glib-tools=2.82.2=h4394cf3_1
  - gst-plugins-base=1.24.7=hb0a98b8_0
  - gstreamer=1.24.7=h5006eae_0
  - icu=75.1=he0c23c2_0
  - intel-openmp=2024.2.1=h57928b3_1083
  - kiwisolver=1.4.8=py312hc790b64_0
  - krb5=1.21.3=hdf4eb48_0
  - lcms2=2.17=hbcf6048_0
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=29_h576b46c_mkl
  - libbrotlicommon=1.1.0=h2466b09_2
  - libbrotlidec=1.1.0=h2466b09_2
  - libbrotlienc=1.1.0=h2466b09_2
  - libcblas=3.9.0=29_h7ad3364_mkl
  - libclang13=19.1.7=default_ha5278ca_1
  - libdeflate=1.23=h9062f6e_0
  - libexpat=2.6.3=he0c23c2_0
  - libffi=3.4.2=h8ffe710_5
  - libgcc=14.2.0=h1383e82_1
  - libglib=2.82.2=h7025463_1
  - libgomp=14.2.0=h1383e82_1
  - libhwloc=2.11.2=default_ha69328c_1001
  - libiconv=1.17=hcfcfb64_2
  - libintl=0.22.5=h5728263_3
  - libintl-devel=0.22.5=h5728263_3
  - libjpeg-turbo=3.0.0=hcfcfb64_1
  - liblapack=3.9.0=29_hacfb0e4_mkl
  - liblzma=5.6.4=h2466b09_0
  - libogg=1.3.5=h2466b09_0
  - libpng=1.6.46=had7236b_0
  - libsqlite=3.46.1=h2466b09_0
  - libtiff=4.7.0=h797046b_3
  - libvorbis=1.3.7=h0e60522_0
  - libwebp-base=1.5.0=h3b0e114_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_9
  - libxcb=1.17.0=h0e4246c_0
  - libxml2=2.13.5=he286e8c_1
  - libzlib=1.3.1=h2466b09_2
  - matplotlib=3.8.0=py312h2e8e312_2
  - matplotlib-base=3.8.0=py312h26ecaf7_2
  - mkl=2024.2.2=h66d3029_15
  - munkres=1.1.4=pyh9f0ad1d_0
  - numpy=1.26.4=py312h8753938_0
  - openjpeg=2.5.3=h4d64b90_0
  - openpyxl=3.1.5=py312he70551f_1
  - openssl=3.5.0=ha4e3fda_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312h72972c8_1
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=h3d7b363_2
  - pillow=11.1.0=py312h078707f_0
  - pip=24.2=pyh8b19718_1
  - ply=3.11=pyhd8ed1ab_3
  - pthread-stubs=0.4=h0e40799_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.1=pyhd8ed1ab_0
  - pyqt=5.15.9=py312he09f080_5
  - pyqt5-sip=12.12.2=py312h53d5487_5
  - python=3.12.6=hce54a09_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2025.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - qt-main=5.15.8=h264fbc2_26
  - scipy=1.15.1=py312h928f2a1_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=75.1.0=pyhd8ed1ab_0
  - sip=6.7.12=py312h53d5487_0
  - six=1.17.0=pyhd8ed1ab_0
  - statsmodels=0.14.4=py312h1a27103_0
  - tbb=2021.13.0=h62715c5_1
  - tk=8.6.13=h5226925_1
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhd8ed1ab_1
  - tornado=6.4.2=py312h4389bb4_0
  - tzdata=2024a=h8827d51_1
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=16.0.0=py312h4389bb4_0
  - vc=14.3=h8a93ad2_21
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wheel=0.44.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.12=h0e40799_0
  - xorg-libxdmcp=1.1.5=h0e40799_0
  - zstandard=0.23.0=py312h7606c53_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - attrs==25.3.0
      - cattrs==25.1.1
      - charset-normalizer==3.4.1
      - cryptography==45.0.5
      - distro==1.9.0
      - embreex==2.17.7.post6
      - fjson==0.1.6
      - getmac==0.9.5
      - idna==3.10
      - joblib==1.5.1
      - legacy-quadpy==0.16.10
      - llvmlite==0.44.0
      - markdown-it-py==3.0.0
      - matplotx==0.3.10
      - mdurl==0.1.2
      - mpmath==1.3.0
      - numba==0.61.0
      - platformdirs==4.3.6
      - pooch==1.8.2
      - progress==1.6
      - pvlib==0.11.2
      - py-machineid==0.8.0
      - pygments==2.19.2
      - pythermalcomfort==3.0.0
      - pytz==2025.1
      - pyviewfactor==0.0.16
      - pyvista==0.45.2
      - pyvistaqt==0.11.2
      - qtpy==2.4.3
      - requests==2.32.3
      - requests-cache==1.2.1
      - rich==14.0.0
      - rich-argparse==1.7.1
      - scikit-learn==1.7.0
      - scooby==0.10.0
      - sympy==1.14.0
      - threadpoolctl==3.6.0
      - trimesh==4.6.12
      - typing-extensions==4.12.2
      - url-normalize==2.2.1
      - urllib3==2.3.0
      - vtk==9.3.1
      - winregistry==2.1.1
      - x22==0.2.1
      - xlrd==2.0.2
prefix: C:\Users\tgresse\.conda\envs\imotep
